import MainLayout from "@/components/common/layout/MainLayout";
import "@/styles/globals.css";

import { Be_Vietnam_Pro, Inter } from "next/font/google";

const beVietnamPro = Be_Vietnam_Pro({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${beVietnamPro.className} bg-neutral-paleRed text-neutral-darkBlue`}
      >
        <MainLayout>{children}</MainLayout>
      </body>
    </html>
  );
}
